### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by RealMrSHA** [Ela-Fhd/cms_admin_panel#1]
سلام ممنون میشم داکیومنت خود CMS رو که از پکیجش استفاده کردید به اشتراک بزارید. تا حالا از CMS با J's استفاده نکردم جالب شد برام😁👌

**Comment by ElaheFahmideh** [comment]
> سلام ممنون میشم داکیومنت خود CMS رو که از پکیجش استفاده کردید به اشتراک بزارید. تا حالا از CMS با J's استفاده نکردم جالب شد برام😁👌

سلام داکیومنت postman رو به ریپازیتوری اضافه میکنم🌸
